version: '3'

services:
    apache:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        container_name: guspache
        # depends_on:
        #     - mysql
        #     - mailhog_apache
        networks:
            - gus-apache-network

    # mysql:
    #     image: mysql:5.7
    #     restart: always
    #     container_name: craftmysql
    #     ports:
    #         - 3306:3306
    #     environment:
    #         MYSQL_DATABASE: laravel
    #         MYSQL_ROOT_PASSWORD: laravel
    #     volumes:
    #         - ./dockerDBData:/var/lib/mysql
    #     networks:
    #         gus-apache-network:
    #             ipv4_address: 12.0.0.8
    
    # mailhog_apache:
    #     image: mailhog/mailhog
    #     container_name: mailhog_apache
    #     ports:
    #         - 1025:1025
    #         - 8025:8025
    #     networks:
    #          gus-apache-network:
    #             ipv4_address: 12.0.0.10
    
    # redis:
    #     image: redis
    #     container_name: redis
    #     ports:
    #         - 6379:6379
    #     networks:
    #         gus-apache-network:
    #             ipv4_address: 12.0.0.9

networks:
    gus-apache-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "12.0.0.0/16"